enable-magisk-update = true

[Music-anddea]
enabled = false
app-name = "Music"
patches-source = "anddea/revanced-patches"
patches-version = "v2.224.0-dev.8"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea"
build-mode = "apk"
included-patches = "'Custom branding icon YouTube Music'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"

[YouTube-anddea]
enabled = false
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
patches-version = "v2.224.0-dev.8"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea"
build-mode = "apk"
included-patches = "'MaterialYou' 'Custom branding icon YouTube'"
excluded-patches = "'Disable QUIC protocol'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"

[YouTube-anddea-TEST]
enabled = true
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
patches-version = "v2.224.0-dev.8"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea"
build-mode = "apk"
included-patches = "'MaterialYou' 'Custom branding icon YouTube'"
excluded-patches = "'Disable QUIC protocol' 'Enable tablet mini player' 'Enable tablet navigation bar' 'Enable wide search bar' 'Hide navigation buttons' 'Hide toolbar button'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"

[Reddit-anddea]
enabled = false
app-name = "Reddit"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea"
build-mode = "apk"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
arch = "arm64-v8a"

