enable-magisk-update = true
parallel-jobs = 1

patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea"

patches-version = "dev"

[Music-Anddea]
enabled = true
app-name = "Music"
included-patches = "'Custom branding icon for YouTube Music'"
excluded-patches = "'Enable debug logging' 'Restore old style library shelf' 'Return YouTube Dislike'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"

[YouTube-Anddea]
enabled = true
app-name = "YouTube"
included-patches = "'Custom branding icon for YouTube' 'MaterialYou'"
excluded-patches = "'Alternative thumbnails' 'Enable debug logging' 'Enable gradient loading screen' 'Return YouTube Dislike' 'Spoof app version'" #'Disable QUIC protocol'
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
