enable-magisk-update = true
patches-source = "anddea/revanced-patches" #inotia00/revanced-patches
integrations-source = "anddea/revanced-integrations" #inotia00/revanced-integrations
#cli-source = "inotia00/revanced-cli"
rv-brand = "anddea" #ReVanced Extended

patches-version = "v2.228.0-dev.11"
integrations-version = "v0.155.0-dev.6"

#############################################################################################################################################################

[Music]
enabled = true
app-name = "Music"
included-patches = "'Custom branding icon for YouTube Music'"
excluded-patches = "'Enable Cairo splash animation' 'Enable debug logging' 'Restore old style library shelf' 'Return YouTube Dislike'"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"

#############################################################################################################################################################

[YouTube]
enabled = true
app-name = "YouTube"
included-patches = "'Custom branding icon for YouTube' 'MaterialYou'"
excluded-patches = "'Alternative thumbnails' 'Disable QUIC protocol' 'Enable debug logging' 'Enable gradient loading screen' 'Return YouTube Dislike'"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

#############################################################################################################################################################

[Reddit-Legacy]
enabled = true
app-name = "Reddit"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

#############################################################################################################################################################

[Reddit]
enabled = false
app-name = "Reddit"
patches-source = "inotia00/revanced-patches-arsclib"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli-arsclib"
version = "2024.28.1"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
