compression-level = 9
enable-magisk-update = true

[Reddit]
enabled = false
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Music-ReX]
enabled = true
app-name = "Music"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "ReX"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[YouTube-ReX]
enabled = true
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "ReX"
build-mode = "apk"
arch = "arm64-v8a"
excluded-patches = "'Custom package name' 'Disable QUIC protocol' 'Enable tablet mini player' 'Enable tablet navigation bar' 'Return YouTube Dislike' 'Theme'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
