enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music-anddea]
enabled = false
app-name = "Music"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea"
build-mode = "apk"
uptodown-dlurl = "https://youtube-music.ru.uptodown.com/android"
arch = "arm64-v8a"

[YouTube-anddea]
enabled = true
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
patches-version = "v2.224.0-dev.1"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea"
build-mode = "apk"
included-patches = "'Premium heading' 'MaterialYou'"
excluded-patches = "'Disable QUIC protocol' 'Enable tablet mini player' 'Enable tablet navigation bar' 'Enable wide search bar'"
uptodown-dlurl = "https://youtube.ru.uptodown.com/android"
arch = "arm64-v8a"
