enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music-anddea]
enabled = true
app-name = "Music"
patches-source = "anddea/revanced-patches"
patches-version = "Pre-release"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea"
build-mode = "apk"
included-patches = "'Custom branding icon YouTube Music'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"

[YouTube-anddea]
enabled = true
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
patches-version = "v2.224.0-dev.4"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea"
build-mode = "apk"
included-patches = "'MaterialYou' 'Custom branding icon YouTube'"
excluded-patches = "'Disable HDR video' 'Disable QUIC protocol'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
