enable-magisk-update = true
parallel-jobs = 1

patches-source = "anddea/revanced-patches"
cli-source = "j-hc/revanced-cli"
rv-brand = "Anddea"

patches-version = "dev"
cli-version = "latest"
arch = "arm64-v8a"
build-mode = "apk"

[Music-Extended]
enabled = true
app-name = "Music"
included-patches = "'Custom branding icon for YouTube Music'"
excluded-patches = "'Enable debug logging' 'Restore old style library shelf' 'Return YouTube Dislike'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"

[YouTube-Extended]
enabled = true
app-name = "YouTube"
included-patches = "'Custom branding icon for YouTube' 'MaterialYou'"
excluded-patches = "'Alternative thumbnails' 'Enable debug logging' 'Enable gradient loading screen' 'Return YouTube Dislike' 'Spoof app version'" #'Disable QUIC protocol'
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[Reddit-Extended]
enabled = true
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
