enable-magisk-update = false
patches-source = "anddea/revanced-patches" #inotia00/revanced-patches
integrations-source = "anddea/revanced-integrations" #inotia00/revanced-integrations
#cli-source = "inotia00/revanced-cli"
rv-brand = "anddea" #ReVanced Extended
build-mode = "apk"
arch = "arm64-v8a"

patches-version = "v2.227.0-dev.24"
integrations-version = "v0.154.0-dev.9"

##################################################################################################################################################

[Music]
enabled = true
app-name = "Music"
included-patches = "'Custom branding icon for YouTube Music'"
excluded-patches = "'Enable debug logging' 'Enable Cairo splash animation' 'Restore old style library shelf' 'Return YouTube Dislike'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"

[YouTube]
enabled = true
app-name = "YouTube"
included-patches = "'Custom branding icon for YouTube' 'MaterialYou'"
excluded-patches = "'Disable QUIC protocol' 'Enable debug logging' 'Enable gradient loading screen' 'Return YouTube Dislike'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Reddit]
enabled = false
app-name = "Reddit"
#version = "latest"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

##################################################################################################################################################

#[Music-Extended]
#excluded-patches = "'Custom package name' 'Enable debug logging' 'Restore old style library shelf' 'Return YouTube Dislike'"

#[YouTube-Extended]
#included-patches = "'MaterialYou'"
#excluded-patches = "'Custom package name' 'Disable QUIC protocol' 'Enable debug logging' 'Enable gradient loading screen' 'Return YouTube Dislike'"
