enable-magisk-update = true
parallel-jobs = 1

#patches-source = "anddea/revanced-patches"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
#rv-brand = "anddea"

patches-version = "dev"
cli-version = "latest"

[Music-Extended]
enabled = false
app-name = "Music"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = "'Custom branding icon for YouTube Music'"
excluded-patches = "'Enable debug logging' 'Restore old style library shelf' 'Return YouTube Dislike' 'Return YouTube Username'"
patcher-args = "-e 'Translations for YouTube Music' -OselectedTranslations=ru-rRU -OselectedStringResources=ru -e 'GmsCore support' -OcheckGmsCore=false -e 'Custom branding icon for YouTube Music' -OappIcon=revancify_blue"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"

[YouTube-Extended]
enabled = false
app-name = "YouTube"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = "'Custom branding icon for YouTube' 'MaterialYou'"
excluded-patches = "'Alternative thumbnails' 'Enable debug logging' 'Enable gradient loading screen' 'Return YouTube Dislike' 'Spoof app version' 'Return YouTube Username'" #'Disable QUIC protocol'
patcher-args = "-e 'Translations for YouTube' -OselectedTranslations=ru-rRU -OselectedStringResources=ru -e 'GmsCore support' -OcheckGmsCore=false -e 'Custom branding icon for YouTube' -OappIcon=revancify_blue"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Reddit-Extended]
enabled = true
arch = "arm64-v8a"
#version = "2025.02.0"
build-mode = "apk"
rv-brand = "ReVanced Extended"
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://reddit-official-app.ru.uptodown.com/android"

[Twitter]
enabled = false
build-mode = "apk"
patches-source = "revanced/revanced-patches"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
apkmirror-dpi = "120-640dpi"
uptodown-dlurl = "https://twitter.en.uptodown.com/android/download/"
