enable-magisk-update = false
parallel-jobs = 1

patches-source = "anddea/revanced-patches"
rv-brand = "ReVanced Extended"

patches-version = "dev"
cli-version = "latest"

[Music-Extended]
enabled = true
app-name = "Music"
arch = "arm64-v8a"
build-mode = "apk"
excluded-patches = "'Certificate spoof' 'Change share sheet' 'Change start page' 'Disable DRC audio' 'Disable QUIC protocol' 'Enable OPUS codec' 'Enable debug logging' 'Restore old style library shelf' 'Return YouTube Dislike' 'Return YouTube Username' 'Spoof app version' 'Watch history'"
patcher-args = "-e 'Settings for YouTube Music' -OrvxSettingsLabel='Revanced Extended' -e 'Translations for YouTube Music' -OselectedTranslations=ru-rRU -OselectedStringResources=ru -e 'GmsCore support' -OcheckGmsCore=false -e 'Custom branding icon for YouTube Music' -OappIcon=revancify_blue"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.ru.uptodown.com/android"

[YouTube-Extended-anddea]
enabled = true
app-name = "YouTube"
arch = "arm64-v8a"
build-mode = "apk"
excluded-patches = "'Alternative thumbnails' 'Bypass image region restrictions' 'Change share sheet' 'Change start page' 'Custom Shorts action buttons' 'Disable QUIC protocol' 'Disable forced auto audio tracks' 'Disable haptic feedback' 'Disable layout updates' 'Enable OPUS codec' 'Enable debug logging' 'Enable gradient loading screen' 'Hide feed flyout menu' 'Hook YouTube Music actions' 'Hook download actions' 'Return YouTube Dislike' 'Return YouTube Username' 'Spoof app version' 'Spoof watch history'"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=revancify_blue -e 'GmsCore support' -OcheckGmsCore=false -e 'Settings for YouTube' -OrvxSettingsLabel='Revanced Extended' -e 'Translations for YouTube' -OselectedTranslations=ru-rRU -OselectedStringResources=ru -e 'MaterialYou' -e 'Theme'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[YouTube-Extended-inotia00]
enabled = true
app-name = "YouTube-Inotia00"
arch = "arm64-v8a"
build-mode = "apk"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
excluded-patches = "'Alternative thumbnails' 'Bypass image region restrictions' 'Change share sheet' 'Change start page' 'Custom Shorts action buttons' 'Disable QUIC protocol' 'Disable forced auto audio tracks' 'Disable haptic feedback' 'Disable layout updates' 'Enable OPUS codec' 'Enable debug logging' 'Enable gradient loading screen' 'Hide feed flyout menu' 'Hook YouTube Music actions' 'Hook download actions' 'Return YouTube Dislike' 'Return YouTube Username' 'Spoof app version' 'Watch history'"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=revancify_blue -e 'GmsCore support' -OcheckGmsCore=false -e 'Settings for YouTube' -OrvxSettingsLabel='Revanced Extended' -e 'Translations for YouTube' -OselectedTranslations=ru-rRU -OselectedStringResources=ru -e 'MaterialYou' -e 'Theme'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Reddit-Extended]
enabled = true
arch = "arm64-v8a"
build-mode = "apk"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
uptodown-dlurl = "https://reddit-official-app.ru.uptodown.com/android"
#apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

[Twitter]
enabled = false
arch = "arm64-v8a"
build-mode = "apk"
patches-source = "revanced/revanced-patches"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
apkmirror-dpi = "120-640dpi"
uptodown-dlurl = "https://twitter.en.uptodown.com/android/download/"
