enable-magisk-update = true

[Music-anddea]
enabled = true
app-name = "Music"
patches-source = "anddea/revanced-patches"
patches-version = "v2.224.0-dev.5"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea"
build-mode = "apk"
included-patches = "'Custom branding icon YouTube Music'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"

[YouTube-anddea]
enabled = true
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
patches-version = "v2.224.0-dev.5"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea"
build-mode = "apk"
included-patches = "'MaterialYou' 'Custom branding icon YouTube'"
excluded-patches = "'Disable QUIC protocol'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
