enable-magisk-update = false

##################################################################################################################################################

[Music-anddea]
enabled = true
app-name = "Music"
patches-source = "anddea/revanced-patches"
patches-version = "v2.227.0-dev.15"
integrations-source = "anddea/revanced-integrations"
integrations-version = "v0.154.0-dev.5"
included-patches = "'Custom branding icon YouTube Music'"
excluded-patches = "'Custom package name' 'Enable debug logging' 'Restore old style library shelf' 'Return YouTube Dislike'"
rv-brand = "anddea"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"

[YouTube-anddea]
enabled = true
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
patches-version = "v2.227.0-dev.15"
integrations-source = "anddea/revanced-integrations"
integrations-version = "v0.154.0-dev.5"
included-patches = "'MaterialYou' 'Custom branding icon YouTube'"
excluded-patches = "'Custom package name' 'Disable QUIC protocol' 'Enable debug logging' 'Enable gradient loading screen' 'Return YouTube Dislike'"
rv-brand = "anddea"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Reddit-anddea]
enabled = true
app-name = "Reddit"
version = "latest"
patches-source = "anddea/revanced-patches"
patches-version = "v2.227.0-dev.15"
integrations-source = "anddea/revanced-integrations"
integrations-version = "v0.154.0-dev.5"
rv-brand = "anddea"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

##################################################################################################################################################

[Music-Extended]
enabled = false
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
excluded-patches = "'Custom package name' 'Enable debug logging' 'Restore old style library shelf' 'Return YouTube Dislike'"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"

[YouTube-Extended]
enabled = false
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
included-patches = "'MaterialYou'"
excluded-patches = "'Custom package name' 'Disable QUIC protocol' 'Enable debug logging' 'Enable gradient loading screen' 'Return YouTube Dislike'"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Reddit-Extended]
enabled = false
app-name = "Reddit"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
