enable-magisk-update = true
parallel-jobs = 1

patches-source = "inotia00/revanced-patches"
#cli-source = "j-hc/revanced-cli"
cli-source = "inotia00/revanced-cli"
rv-brand = "anddea"

patches-version = "dev"
cli-version = "latest"

[Music-Extended]
enabled = true
app-name = "Music"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = "'Custom branding icon for YouTube Music'"
excluded-patches = "'Enable debug logging' 'Restore old style library shelf' 'Return YouTube Dislike'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
patcher-args = "-e 'Translations for YouTube Music' -OselectedTranslations=ru-rRU -OselectedStringResources=ru -e 'Custom branding icon for YouTube Music' -OappIcon=revancify_blue"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[YouTube-Extended]
enabled = true
app-name = "YouTube"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = "'Custom branding icon for YouTube' 'MaterialYou'"
excluded-patches = "'Alternative thumbnails' 'Enable debug logging' 'Enable gradient loading screen' 'Return YouTube Dislike' 'Spoof app version'" #'Disable QUIC protocol'
patcher-args = "-e 'Translations for YouTube' -OselectedTranslations=ru-rRU -OselectedStringResources=ru -e 'Custom branding icon for YouTube' -OappIcon=revancify_blue"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[Reddit-Extended]
enabled = false
arch = "arm64-v8a"
build-mode = "apk"
patches-source = "inotia00/revanced-patches"
rv-brand = "ReVanced Extended"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
